name: Build Database

on:
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 22
    - run: npm install

    - name: Build database
      run: node tasks/build_database.js
      env: 
        firebase: ${{ secrets.FIREBASE }}
        error_id: ${{ secrets.WEBHOOK_ID }}
        error_token: ${{ secrets.WEBHOOK_TOKEN }}
